//
//  CleanRouter.swift
//  TicTacToe
//
//  Created by Кирилл Пигалкин on 23.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CleanRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CleanDataPassing
{
  var dataStore: CleanDataStore? { get }
}

class CleanRouter: NSObject, CleanRoutingLogic, CleanDataPassing
{
  weak var viewController: CleanViewController?
  var dataStore: CleanDataStore?

  // MARK: Navigation
    
  
  func navigateToSomewhere(source: CleanViewController, destination: AnimationViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
//  func passDataToSomewhere(source: CleanDataStore, destination: inout SomewhereDataStore)
//  {
//      destination.name = source.name
//  }
}
