//
//  CleanPresenter.swift
//  TicTacToe
//
//  Created by Кирилл Пигалкин on 23.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CleanPresentationLogic
{
  func presentSomething(response: Clean.Something.Response)
}

class CleanPresenter: CleanPresentationLogic
{
  weak var viewController: CleanDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Clean.Something.Response)
  {
    let viewModel = Clean.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
