//
//  CleanInteractor.swift
//  TicTacToe
//
//  Created by Кирилл Пигалкин on 23.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CleanBusinessLogic
{
  func doSomething(request: Clean.Something.Request)
}

protocol CleanDataStore
{
  //var name: String { get set }
}

class CleanInteractor: CleanBusinessLogic, CleanDataStore
{
  var presenter: CleanPresentationLogic?
  var worker: CleanWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Clean.Something.Request)
  {
    worker = CleanWorker()
    worker?.doSomeWork()
    
    let response = Clean.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
